version: "3"

services:
  holidayservice:
    image: ghcr.io/umputun/holiday:master
    build: .
    volumes:
      - db-data:/code
    ports:
      - "8000"

  scheduler:
    image: ghcr.io/umputun/cronn
    entrypoint: ['/srv/cronn',  '--log.enabled', '--command="0 0 * * * /usr/bin/curl -X POST http://holidayservice:8000/holidays/ -u admin:Lapatusik"']

  nginx:
    image: nginx:latest
    depends_on:
      - holidayservice
    volumes:
      - ./etc/service.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data:
